#portal-ext.properties
module.framework.properties.osgi.console=localhost:11312

company.security.strangers.verify=false
enterprise.product.enterprise.search.enabled=false
terms.of.use.required=false
passwords.default.policy.change.required=false

admin.email.from.address=test@liferay.com
admin.email.from.name=Test Test

locale.default=en_US

notification.email.template.enabled=true
company.default.locale=en_US
company.default.time.zone=UTC
company.default.web.id=liferay.com
default.admin.email.address.prefix=test
default.admin.password=test
setup.wizard.enabled=false
index.on.startup=false
axis.servlet.hosts.allowed=
tunnel.servlet.hosts.allowed=
google.client.id.1=REDACTED
google.client.secret.1=REDACTED
# jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
# jdbc.default.url=jdbc:mysql://localhost:3307/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
# jdbc.default.username=root
# jdbc.default.password=root

# Disable theme caching
theme.css.fast.load=false
# theme.images.fast.load=true
# theme.js.fast.load=true

# Disable layout template caching
layout.template.cache.enabled=false

# For JSP caching:
web.server.display.node=false
com.liferay.servlet.jsp.debug=true

javascript.fast.load=false
combo.check.timestamp=tru
freemarker.engine.cache.storage=soft:1
freemarker.engine.modification.check.interval=0
minifier.enabled=true
com.liferay.portal.servlet.filters.cache.CacheFilter=false
com.liferay.portal.servlet.filters.etag.ETagFilter=false
com.liferay.portal.servlet.filters.header.HeaderFilter=false
com.liferay.portal.servlet.filters.themepreview.ThemePreviewFilter=true
users.reminder.queries.enabled=false
users.reminder.queries.custom.question.enabled=false
mail.send.blacklist=
mail.session.mail=false
mail.session.mail.pop3.host=localhost
mail.session.mail.pop3.password=
mail.session.mail.pop3.port=110
mail.session.mail.pop3.user=
mail.session.mail.smtp.auth=false
mail.session.mail.smtp.host=localhost
mail.session.mail.smtp.password=
mail.session.mail.smtp.port=3333
mail.session.mail.smtp.user=
mail.session.mail.store.protocol=pop3
mail.session.mail.transport.protocol=smtp
virtual.hosts.valid.hosts=*
upgrade.database.auto.run=true
analytics.cloud.domain.allowed=*
feature.flag.ui.visible[dev]=true

default.layout.template.id=1_column
company.default.time.zone=America/Los_Angeles

feature.flag.LPD-00001=false  
feature.flag.LPD-00001.dependencies=LPD-00000
feature.flag.LPD-00001.type=dev

feature.flag.LPD-00000=false
feature.flag.LPD-00000.type=dev

# feature.flag.LPS-155284=true
