#!/bin/bash
# Usage: lp worktree start [-b] [branch-name]
# If no branch is given, uses the current directory.
# -b: run the build step (skipped by default)

set -e

BUILD=false

while getopts ":b" opt; do
    case $opt in
        b) BUILD=true ;;
        \?) echo "Unknown option: -$OPTARG" >&2; exit 1 ;;
    esac
done
shift $((OPTIND - 1))

source "$(dirname "${BASH_SOURCE[0]}")/../config"

BRANCH=$1

if [ -z "$BRANCH" ]; then
    WORKTREE_DIR=$(pwd)
else
    lp_branch_vars "$BRANCH"
fi

BUNDLE_DIR=$(grep 'app.server.parent.dir' "$WORKTREE_DIR/app.server.me.properties" | cut -d'=' -f2)

cd "$WORKTREE_DIR"

if [ "$BUILD" = true ]; then
    echo "Removing bundle directory '$BUNDLE_DIR'..."
    rm -rf "$BUNDLE_DIR"

    echo "Building in $WORKTREE_DIR..."

    ant setup-profile-dxp
    ant all
fi

echo "Starting server from $BUNDLE_DIR..."
cd "$BUNDLE_DIR"/tomcat-*/bin
./catalina.sh jpda run
